### ISSUE TITLE
Files upload on Glitch does not work with Firefox

### ISSUE THREAD

**Issue by maymgr** [emlyon/Designing-With-Web#10] opened 2018-10-08 13:32 UTC
![error](https://user-images.githubusercontent.com/43471478/46611820-32153a00-cb0f-11e8-8336-5cb6e84f65ec.jpeg)
Hello,
I cannot upload images on glitch with firefow. It worked perfectly well for part 3 but I cannot do it anymore

**Comment by MAKIO135** [comment] 2018-10-08 13:40
Hello,

It seems to be an issue on Glitch, I noticed them so they should fix it soon.

**Comment by MAKIO135** [comment] 2018-10-08 14:43
Are you using Firefox?

**Comment by MAKIO135** [comment] 2018-10-08 14:47
![capture d ecran 2018-10-08 a 16 45 57](https://user-images.githubusercontent.com/1162231/46615909-b076d980-cb19-11e8-9515-b1c65e89db34.png)
Glitch confirmed the bug.
As an alternative for now, this works on Chrome.

**Comment by MelanieRupert** [comment] 2018-10-09 20:42
Hi, 

It doesn't work on Chrome neither : 

![image](https://user-images.githubusercontent.com/43700756/46697255-80603100-cc14-11e8-9f04-e1e1db7cade5.png)

**Comment by MAKIO135** [comment] 2018-10-09 21:18
@MelanieRupert sign in first

**Comment by MAKIO135** [comment] 2019-01-07 16:43
this seems to be fixed now

**Closed by MAKIO135** 2019-01-07 16:43 UTC
Labels: bug
